baseurl = "https://adventures.michaelfbryan.com/"
title = "Michael-F-Bryan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = false
googleAnalytics = "G-M80ZBKQHKV"
enableGitInfo = true
enableEmoji = true

pygmentsStyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
author = "Michael-F-Bryan"
info = "Rustacean, Freelancer, and Open-Source Enthusiast"
description = "A place to document my thoughts and experiments"
keywords = "blog,developer,personal"
customCSS = ["css/master.css"]
customJS = ["js/mermaid.min.js", "js/index.js"]
commit = "https://github.com/Michael-F-Bryan/adventures.michaelfbryan.com/tree"
toc_reading_time_threshold = 15
math = true
colorscheme = "auto"

[markup.goldmark.renderer]
unsafe = true

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/Michael-F-Bryan"

[[params.social]]
name = "GitLab"
icon = "fa fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/Michael-F-Bryan"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/michael-bryan-564889199/"

[[params.social]]
name = "Contact Me"
icon = "fa fa-envelope fa-2x"
weight = 5
url = "mailto:consulting@michaelfbryan.com"

[[params.social]]
name = "RSS"
icon = "fa fa-rss fa-2x"
weight = 6
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Blog"
url  = "/posts/"
[[menu.main]]
name = "About"
url = "/about/"
