baseurl = "http://adventures.michaelfbryan.com/"
title = "Michael-F-Bryan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Michael-F-Bryan"
info = "Professional Software Engineer"
description = "A place to document my thoughts and experiments"
keywords = "blog,developer,personal"

[[params.social]]
name = "Github"
icon = "fab fa-github fa-2x"
weight = 1
url = "https://github.com/Michael-F-Bryan"
[[params.social]]
name = "GitLab"
icon = "fab fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/Michael-F-Bryan"
[[params.social]]
name = "Contact Me"
icon = "fas fa-envelope fa-2x"
weight = 3
url = "mailto:michaelfbryan@gmail.com"

[[menu.main]]
name = "Blog"
url  = "/posts/"
[[menu.main]]
name = "About"
url = "/about/"