baseurl = "https://adventures.michaelfbryan.com/"
title = "Michael-F-Bryan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = false
googleAnalytics = "UA-78714693-3"
enableGitInfo = true
enableEmoji = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Michael-F-Bryan"
info = "I like making things and solving cool problems"
description = "A place to document my thoughts and experiments"
keywords = "blog,developer,personal"
custom_css = ["css/master.css"]
custom_js = ["js/mermaid.min.js", "js/index.js"]
commit = "https://github.com/Michael-F-Bryan/adventures.michaelfbryan.com/tree"
toc_reading_time_threshold = 15

[markup.goldmark.renderer]
unsafe= true

[[params.social]]
name = "Github"
icon = "fab fa-github fa-2x"
weight = 1
url = "https://github.com/Michael-F-Bryan"
[[params.social]]
name = "GitLab"
icon = "fab fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/Michael-F-Bryan"
[[params.social]]
name = "Contact Me"
icon = "fas fa-envelope fa-2x"
weight = 3
url = "mailto:michaelfbryan@gmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
weight = 6
url = "https://adventures.michaelfbryan.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Blog"
url  = "/posts/"
[[menu.main]]
name = "About"
url = "/about/"

[[deployment.targets]]
name = "Amazon S3"
URL = "s3://adventures.michaelfbryan.com?region=ap-southeast-2"

[[deployment.matchers]]
#  Cache static assets for 20 years.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
