name: Metrics

# Copied from https://github.com/ahdinosaur/ahdinosaur
on:
  # Schedule updates (each day)
  schedule:
    - cron: "0 0 23 * *" # 23:00 UTC
  # Run workflow manually
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          filename: static/img/metrics.overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_order: base.header, base.activity+community, base.repositories
          config_display: columns
          base: header, activity, community, repositories, metadata
          base_indepth: yes

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: static/img/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_order: languages
          base: ""
          debug: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_details: percentage, bytes-size, lines
          plugin_languages_ignored: G-code, Yacc
          plugin_languages_indepth: yes
          plugin_languages_threshold: 1%
