name: Staging

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build
      run: hugo --buildDrafts --buildFuture
    - name: Authenticate with GCS
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Upload
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'public'
        destination: 'staging.adventures.michaelfbryan.com'
        parent: false
